import Reveal from "./Reveal";

export default function ResearchOutput() {
  return (
    <Reveal>
      <section id="research-output" className="bg-white py-32">
        <div className="mx-auto max-w-7xl px-6">

          <div className="text-center">

            <div className="inline-flex rounded-full border px-4 py-2 text-sm text-gray-600">
              Research Output
            </div>

            <h2 className="mt-8 text-5xl font-bold md:text-6xl">
              ScholarFlow:
              <br />
              AI-Native Research Workspace
            </h2>

            <p className="mx-auto mt-6 max-w-3xl text-lg text-gray-600">
              ScholarFlow integrates literature retrieval,
              cross-paper analysis, knowledge graphs and
              scientific writing into a unified research workflow.
            </p>

          </div>

          <div className="mt-20 rounded-[36px] border bg-white p-10 shadow-2xl">

            {/* Header */}

            <div className="border-b pb-8">

              <div className="text-sm text-gray-500">
                Generated Research Package
              </div>

              <h3 className="mt-3 text-4xl font-bold">
                ScholarFlow:
                AI-Native Research Workspace
              </h3>

              <div className="mt-4 flex flex-wrap gap-3 text-sm text-gray-500">
                <span>12 Papers</span>
                <span>•</span>
                <span>53 Evidence Nodes</span>
                <span>•</span>
                <span>18 Knowledge Relations</span>
                <span>•</span>
                <span>Generated by ScholarFlow Agent</span>
              </div>

            </div>

            {/* Abstract */}

            <div className="mt-10">

              <h4 className="text-2xl font-semibold">
                Research Outcome
              </h4>

              <p className="mt-4 leading-8 text-gray-700">
                ScholarFlow is an AI-native research workspace
                designed to support the complete scientific workflow.

                <br />
                <br />

                The system integrates literature retrieval,
                cross-paper analysis, knowledge graph construction,
                evidence synthesis and scientific writing into
                a single collaborative environment.

                <br />
                <br />

                By maintaining structured research context and
                traceable evidence, ScholarFlow enables researchers
                to move from information collection to scientific
                insight more efficiently.
              </p>

            </div>

            {/* Key Findings */}

            <div className="mt-12">

              <h4 className="text-2xl font-semibold">
                Key Capabilities
              </h4>

              <div className="mt-6 grid gap-6 lg:grid-cols-3">

                <div className="rounded-2xl bg-gray-50 p-6">

                  <div className="text-sm text-gray-500">
                    CAPABILITY 01
                  </div>

                  <h5 className="mt-2 font-semibold">
                    Literature Intelligence
                  </h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Research findings from multiple papers are
                    organized into a unified knowledge space.
                  </p>

                </div>

                <div className="rounded-2xl bg-gray-50 p-6">

                  <div className="text-sm text-gray-500">
                    CAPABILITY 02
                  </div>

                  <h5 className="mt-2 font-semibold">
                    Evidence Traceability
                  </h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Every conclusion remains linked to
                    supporting evidence and source material.
                  </p>

                </div>

                <div className="rounded-2xl bg-gray-50 p-6">

                  <div className="text-sm text-gray-500">
                    CAPABILITY 03
                  </div>

                  <h5 className="mt-2 font-semibold">
                    Scientific Workflow
                  </h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Research activities remain connected from
                    retrieval and analysis to final writing.
                  </p>

                </div>

              </div>

            </div>

            {/* Research Assets */}

            <div className="mt-12 rounded-3xl bg-gray-50 p-8">

              <h4 className="text-2xl font-semibold">
                Research Assets Generated
              </h4>

              <div className="mt-8 flex flex-col items-center gap-4">

                <div className="rounded-xl border bg-white px-6 py-3">
                  Literature Library
                </div>

                <div className="text-sm text-gray-500">
                  12 linked research papers
                </div>

                <div>↓</div>

                <div className="rounded-xl border bg-white px-6 py-3">
                  Evidence Repository
                </div>

                <div className="text-sm text-gray-500">
                  53 extracted evidence nodes
                </div>

                <div>↓</div>

                <div className="rounded-xl bg-black px-8 py-4 font-semibold text-white">
                  Knowledge Graph
                </div>

                <div className="text-sm text-gray-500">
                  18 connected concepts and findings
                </div>

                <div>↓</div>

                <div className="rounded-xl border bg-white px-6 py-3">
                  Research Draft
                </div>

                <div className="text-sm text-gray-500">
                  Survey and synthesis report generated
                </div>

              </div>

            </div>

            {/* Draft */}

            <div className="mt-12 rounded-3xl border p-8">

              <h4 className="text-2xl font-semibold">
                Generated Insight
              </h4>

              <p className="mt-6 leading-8 text-gray-700">
                Research knowledge becomes significantly
                more valuable when literature, evidence,
                reasoning processes and generated outputs
                remain connected within the same workspace.

                <br />
                <br />

                ScholarFlow enables knowledge accumulation
                across research sessions, allowing evidence
                and insights to be continuously reused,
                verified and expanded over time.
              </p>

            </div>

            {/* Literature */}

            <div className="mt-12 rounded-3xl border p-8">

              <h4 className="text-2xl font-semibold">
                Related Research Areas
              </h4>

              <div className="mt-6 space-y-3 text-sm text-gray-600">

                <div>
                  [1] Research Objects in Scholarly Communication
                </div>

                <div>
                  [2] FAIR Principles for Scientific Data Management
                </div>

                <div>
                  [3] Knowledge Graphs for Scientific Discovery
                </div>

                <div>
                  [4] Retrieval-Augmented Generation for Knowledge-Intensive Tasks
                </div>

                <div>
                  [5] AI Research Assistants and Scientific Workflows
                </div>

              </div>

            </div>

          </div>
        </div>
      </section>
    </Reveal>
  );
}