// C:/Users/lengion/scholarflow-showcase/app/components/ResearchOutput.tsx
import Reveal from "./Reveal";

export default function ResearchOutput() {
  return (
    <Reveal>
      <section id="research-output" className="bg-white py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="text-center">
            <div className="inline-flex rounded-full border px-4 py-2 text-sm text-gray-600">
              Evidence-Grounded Research Output
            </div>

            <h2 className="mt-8 text-5xl font-bold md:text-6xl">
              Persistent Research Memory:
              <br />
              A Unified Research Intelligence Framework
            </h2>

            <p className="mx-auto mt-6 max-w-3xl text-lg text-gray-600">
              This work investigates how research knowledge can persist beyond
              individual conversations, papers and sessions.
            </p>
          </div>

          <div className="mt-20 rounded-[36px] border bg-white p-10 shadow-2xl">
            <div className="border-b pb-8">
              <div className="text-sm text-gray-500">
                Research Survey Draft
              </div>

              <h3 className="mt-3 text-4xl font-bold">
                Persistent Research Memory:
                A Unified Research Intelligence Framework
              </h3>

              <div className="mt-4 flex flex-wrap gap-3 text-sm text-gray-500">
                <span>12 Papers</span>
                <span>•</span>
                <span>53 Evidence Nodes</span>
                <span>•</span>
                <span>18 Knowledge Relations</span>
                <span>•</span>
                <span>Generated by ScholarFlow Agent</span>
              </div>
            </div>

            <div className="mt-10">
              <h4 className="text-2xl font-semibold">Abstract</h4>

              <p className="mt-4 leading-8 text-gray-700">
                This work investigates how research knowledge can persist beyond
                individual conversations, papers and sessions.
                <br />
                <br />
                By integrating retrieval, memory, knowledge graphs and agent
                workflows, ScholarFlow continuously accumulates, organizes and
                reuses scientific knowledge.
                <br />
                <br />
                The resulting system transforms fragmented research activities
                into a persistent research intelligence process.
              </p>
            </div>

            <div className="mt-12">
              <h4 className="text-2xl font-semibold">Key Findings</h4>

              <div className="mt-6 grid gap-6 lg:grid-cols-3">
                <div className="rounded-2xl bg-gray-50 p-6">
                  <div className="text-sm text-gray-500">FINDING 01</div>

                  <h5 className="mt-2 font-semibold">
                    Knowledge Persistence
                  </h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Persistent knowledge survives across sessions and becomes
                    reusable research memory.
                  </p>
                </div>

                <div className="rounded-2xl bg-gray-50 p-6">
                  <div className="text-sm text-gray-500">FINDING 02</div>

                  <h5 className="mt-2 font-semibold">
                    Evidence Traceability
                  </h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Every conclusion maintains links to supporting evidence.
                  </p>
                </div>

                <div className="rounded-2xl bg-gray-50 p-6">
                  <div className="text-sm text-gray-500">FINDING 03</div>

                  <h5 className="mt-2 font-semibold">Research Intelligence</h5>

                  <p className="mt-3 text-sm leading-7 text-gray-600">
                    Accumulated knowledge continuously improves future research
                    tasks.
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-12 rounded-3xl bg-gray-50 p-8">
              <h4 className="text-2xl font-semibold">Evidence Map</h4>

              <div className="mt-8 flex flex-col items-center gap-4">
                <div className="rounded-xl border bg-white px-6 py-3">
                  Literature
                </div>

                <div>↓</div>

                <div className="rounded-xl border bg-white px-6 py-3">
                  Evidence
                </div>

                <div>↓</div>

                <div className="rounded-xl border bg-white px-6 py-3">
                  Insights
                </div>

                <div>↓</div>

                <div className="rounded-xl bg-black px-8 py-4 font-semibold text-white">
                  Knowledge Graph
                </div>

                <div>↓</div>

                <div className="rounded-xl border bg-white px-6 py-3">
                  Research Output
                </div>
              </div>
            </div>

            <div className="mt-12 rounded-3xl border p-8">
              <h4 className="text-2xl font-semibold">
                Generated Draft Excerpt
              </h4>

              <p className="mt-6 leading-8 text-gray-700">
                Persistent research memory allows scientific work to compound
                over time. Knowledge collected in one session remains available
                for later reasoning, synthesis and writing.
              </p>
            </div>

            <div className="mt-12 rounded-3xl border p-8">
              <h4 className="text-2xl font-semibold">
                Supporting Literature
              </h4>

              <div className="mt-12 rounded-3xl border p-8">
                <h4 className="text-2xl font-semibold">
                  Supporting Literature
                </h4>

                <div className="mt-6 space-y-3 text-sm text-gray-600">

                  <div>
                    [1] Research Objects in Scholarly Communication
                  </div>

                  <div>
                    [2] FAIR Principles for Scientific Data Management
                  </div>

                  <div>
                    [3] Knowledge Graphs for Scientific Discovery
                  </div>

                  <div>
                    [4] Retrieval-Augmented Generation for Knowledge-Intensive Tasks
                  </div>

                  <div>
                    [5] Persistent Knowledge Systems for AI Research Assistants
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </Reveal>
  );
}